#include "StrikerLog.h"

DEFINE_LOG_CATEGORY(LogGameplay);
DEFINE_LOG_CATEGORY(LogAI);
DEFINE_LOG_CATEGORY(LogAnimation);
DEFINE_LOG_CATEGORY(LogPhysics);
DEFINE_LOG_CATEGORY(LogReplay);
DEFINE_LOG_CATEGORY(LogRules);
DEFINE_LOG_CATEGORY(LogAudio);
DEFINE_LOG_CATEGORY(LogCamera);
DEFINE_LOG_CATEGORY(LogSave);
DEFINE_LOG_CATEGORY(LogNetworking);
DEFINE_LOG_CATEGORY(LogUI);
