#pragma once
#include "CoreMinimal.h"

PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameplay, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogAI, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogAnimation, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogPhysics, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogReplay, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogRules, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogAudio, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogCamera, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogSave, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogNetworking, Log, All);
PROJECTSTRIKERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogUI, Log, All);
